### ISSUE TITLE
Add Windows support.

### ISSUE THREAD

**Issue by Droid-MAX** [dmsc/iceprog-serprog#1]

**Comment by dmsc** [comment]
Hi!

I suppose you are asking how to do a cross-compile for Windows... from Linux? 

Then, as any simple makefile, just type:
```
make CC=i686-w64-mingw32-gcc
```

**Comment by Droid-MAX** [comment]
It failed, because prompt missing header file "termios.h" 
I found that some of the source files related to the serial function in the flashrom software project have been adapted for the Windows platform, but I still have no idea how to adapt

**Comment by Droid-MAX** [comment]
And from the analysis of the way of accessing serial devices, Linux and Windows systems are completely different, so the best way is to rewrite related functions and pay attention to judging the system platform
